# Exploratory data analysis (EDA) of car data

## Libraries and settings

In [1]:
# Libraries
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from datetime import datetime, timedelta

# seaborn graphics settings
sns.set_theme(color_codes=True)

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Show current working directory
print(os.getcwd())

/workspaces/python_exploratory_data_analysis

## Importing the car data

### Importing the car data

In [2]:
# Columns to read
columns = ["Offer_Id",
            "Type",
            "Price",
            "HP",
            "Mileage",
            "Fuel_Type",
            "Transmission",
            "Dealer_PLZ",
            "Dealer_City",
            "Dealer_Street_House_Nr",
            "Init_Regist_MY",
            "Init_Regist_Month",
            "Init_Regist_Year",
            "Init_Regist_Dt"]

# Read and select variables
df_orig = pd.read_csv("autoscout24_data_enriched_cleaned.csv", sep=",")[columns]

# Remove duplicates
df_orig = df_orig.drop_duplicates()
df_orig.head(5)

# Remove missing values
df = df_orig.dropna()
df.head(5)

,Offer_Id,Type,Price,HP,Mileage,Fuel_Type,Transmission,Dealer_PLZ,Dealer_City,Dealer_Street_House_Nr,Init_Regist_MY,Init_Regist_Month,Init_Regist_Year,Init_Regist_Dt
0,7324420,AUDI A5 Sportback 3.0 TDI quattro S-tronic (Li...,22500,245,75000,Diesel,Automatisiertes Schaltgetriebe,8488,Turbenthal,Mettlenstrasse 3,10.2014,10.0,2014.0,2014-10
1,7512768,MERCEDES-BENZ SLK 200 7G-Tronic (Cabriolet),23749,184,46655,Benzin,Automat sequentiell,3186,Düdingen,Brugerastrasse 60,6.2013,6.0,2013.0,2013-06
2,7512034,MERCEDES-BENZ C 350 Avantgarde 4Matic 7G-Troni...,18500,306,138955,Benzin,Automat sequentiell,1262,Eysins,1262 Eysins,6.2011,6.0,2011.0,2011-06
3,7512728,MERCEDES-BENZ A 45 AMG 4Matic Speedshift 7G-DC...,36000,360,43000,Benzin,Automatisiertes Schaltgetriebe,4314,Zeiningen,Am Stutz 21,8.2015,8.0,2015.0,2015-08
4,7490242,AUDI A5 Sportback 2.0 TFSI Sport quattro S-tro...,48500,252,43300,Benzin,Automatisiertes Schaltgetriebe,3250,Lyss,3250 Lyss,9.2018,9.0,2018.0,2018-09

## Univariate non-graphical exploratory data analysis (EDA)

### Quantiles

In [7]:
df[['Price', 'Mileage', 'HP']].quantile(
    q=[0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]).round(2)

        Price   Mileage     HP
0.05   4000.0   13700.0   90.0
0.10   5900.0   23000.0  110.0
0.25  10900.0   45000.0  150.0
0.50  19900.0   83500.0  204.0
0.75  35900.0  130000.0  306.0
0.90  56900.0  176000.0  405.0
0.95  72500.0  206090.5  469.5

### Shape (number of rows and colums)

In [8]:
# Number of rows and columns
print(df.shape)

(3971, 14)

### Data types

In [10]:
# Data types of df
df.dtypes

Offer_Id                    int64
Type                       object
Price                       int64
HP                          int64
Mileage                     int64
Fuel_Type                  object
Transmission               object
Dealer_PLZ                  int64
Dealer_City                object
Dealer_Street_House_Nr     object
Init_Regist_MY            float64
Init_Regist_Month         float64
Init_Regist_Year          float64
Init_Regist_Dt             object
dtype: object

### Summary statistics of numeric variables

In [11]:
df.describe()

,Offer_Id,Price,HP,Mileage,Dealer_PLZ,Init_Regist_MY,Init_Regist_Month,Init_Regist_Year
count,3.971000e+03,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000,3971.000000
mean,7.242907e+06,27527.641652,235.831025,92952.412491,5522.633594,6.510513,6.309494,2010.189121
std,4.655890e+05,26670.221155,119.671388,61097.990134,2848.337824,3.386338,3.386320,9.610067
min,1.395491e+06,160.000000,16.000000,1.000000,1000.000000,1.194600,1.000000,1929.000000
25%,7.249691e+06,10900.000000,150.000000,45000.000000,3014.000000,3.201800,3.000000,2008.000000
50%,7.408668e+06,19900.000000,204.000000,83500.000000,6003.000000,6.201400,6.000000,2013.000000
75%,7.456806e+06,35900.000000,306.000000,130000.000000,8304.500000,9.201500,9.000000,2016.000000
max,7.512843e+06,428000.000000,772.000000,370000.000000,9657.000000,12.201900,12.000000,2020.000000

### Statistical measures (min, max, std, mean, median, count) for selected variables

In [12]:
# Price
print('Price:',
      'Count:', round(df.Price.count(), 1),
      'Min:', round(df.Price.min(), 1),
      'Max:', round(df.Price.max(), 1),
      'Mean:', round(df.Price.mean(), 1),
      'Median:', round(df.Price.median(), 1),
      'Std:', round(df.Price.std(), 1))

# Mileage
print('Mileate:',
      'Count:', round(df.Mileage.count(), 1),
      'Min:', round(df.Mileage.min(), 1),
      'Max:', round(df.Mileage.max(), 1),
      'Mean:', round(df.Mileage.mean(), 1),
      'Median:', round(df.Mileage.median(), 1),
      'Std:', round(df.Mileage.std(), 1))

Price: Count: 3971 Min: 160 Max: 428000 Mean: 27527.6 Median: 19900.0 Std: 26670.2
Mileate: Count: 3971 Min: 1 Max: 370000 Mean: 92952.4 Median: 83500.0 Std: 61098.0

### Skewness

In [13]:
df[['Price','Mileage', 'HP']].skew()

Price      4.077049
Mileage    0.886538
HP         1.093046
dtype: float64

### Kurtosis

In [14]:
df[['Price','Mileage', 'HP']].kurtosis()

Price      36.506763
Mileage     0.739533
HP          1.226153
dtype: float64

### Extreme values

### Get a list of categories of categorical variable

## Multivariate non-graphical exploratory data analysis (EDA)

### Cross-tabulation

### Pivot tables

### Correlation matrix

### Covariance matrix

## Univariate graphical exploratory data analysis (EDA)

### Line chart (matplotlib)

### Boxplot (seaborn)

### Histogram  (matplotlib)

### Density plot  (seaborn)

### Quantile-Quantile (QQ-) plot

### Barchart  (matplotlib)

### Piechart (matplotlib)

## Multivariate graphical exploratory data analysis (EDA)

### Scatterplot (matplotlib)

### Scatterplot (matplotlib) with regression line

### Scatterplot-matrix (seaborn)

### Hexagonal binning plot  (matplotlib)

### Correlation heatmap (seaborn)

### Bubble plot (seaborn)

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [ ]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')